# Generated by Django 3.2 on 2022-10-12 12:02
import phonenumbers

from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(phone_number):
            flat.owner_pure_phone = f'+7{phone_number.national_number}'
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20221012_1443'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers, move_backward),
    ]
