# Generated by Django 3.2 on 2022-10-12 17:39

from django.db import migrations


def fill_db_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    if flats.exists():
        for flat in flats.iterator():
            Owner.objects.get_or_create(
                owner=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone
            )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    owners.delete()
    owners.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221012_1836'),
    ]

    operations = [
        migrations.RunPython(fill_db_owner, move_backward),
    ]
